
/**************************************************************
 *	
 *	breakSound, 8 bit, 11025Hz,
 *	1 channel, 15011 bytes/channel
 *	Total Size: 1 * 15011 + 4 (header) = 15055 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/suinyun/Desktop/Spring2019/CS2261/M04/breakSound.wav
 *	Time-stamp: Tue Apr 23 13:37:02 2019
 *	
 **************************************************************/

#ifndef __BREAKSOUNDH__
#define __BREAKSOUNDH__

#define BREAKSOUNDFREQ 11025
#define BREAKSOUNDLEN 15011

extern const unsigned char breakSound[15011];

#endif /* __BREAKSOUNDH__ */
