
/**************************************************************
 *	
 *	gameMusic, 8 bit, 11025Hz,
 *	1 channel, 1489248 bytes/channel
 *	Total Size: 1 * 1489248 + 4 (header) = 1489292 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/suinyun/Desktop/Spring2019/CS2261/M04/gameMusic.wav
 *	Time-stamp: Tue Apr 23 14:13:28 2019
 *	
 **************************************************************/

#ifndef __GAMEMUSICH__
#define __GAMEMUSICH__

#define GAMEMUSICFREQ 11025
#define GAMEMUSICLEN 1489248

extern const unsigned char gameMusic[1489248];

#endif /* __GAMEMUSICH__ */
