
/**************************************************************
 *	
 *	gmae, 8 bit, 44100Hz,
 *	1 channel, 66150 bytes/channel
 *	Total Size: 1 * 66150 + 4 (header) = 66194 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/suinyun/Desktop/Spring2019/CS2261/M04/gmae.wav
 *	Time-stamp: Tue Apr 23 14:18:25 2019
 *	
 **************************************************************/

#ifndef __GMAEH__
#define __GMAEH__

#define GMAEFREQ 44100
#define GMAELEN 66150

extern const unsigned char gmae[66150];

#endif /* __GMAEH__ */
