
/**************************************************************
 *	
 *	loseSong, 8 bit, 11025Hz,
 *	1 channel, 80656 bytes/channel
 *	Total Size: 1 * 80656 + 4 (header) = 80700 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/suinyun/Desktop/Spring2019/CS2261/M04/loseSong.wav
 *	Time-stamp: Thu Apr 18 00:09:22 2019
 *	
 **************************************************************/

#ifndef __LOSESONGH__
#define __LOSESONGH__

#define LOSESONGFREQ 11025
#define LOSESONGLEN 80656

extern const unsigned char loseSong[80656];

#endif /* __LOSESONGH__ */
