
/**************************************************************
 *	
 *	SHOOT, 8 bit, 11025Hz,
 *	1 channel, 21024 bytes/channel
 *	Total Size: 1 * 21024 + 4 (header) = 21068 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/suinyun/Desktop/Spring2019/CS2261/M04/SHOOT.wav
 *	Time-stamp: Mon Apr 22 20:18:46 2019
 *	
 **************************************************************/

#ifndef __SHOOTH__
#define __SHOOTH__

#define SHOOTFREQ 11025
#define SHOOTLEN 21024

extern const unsigned char SHOOT[21024];

#endif /* __SHOOTH__ */
