
/**************************************************************
 *	
 *	startMusic, 8 bit, 11025Hz,
 *	1 channel, 697600 bytes/channel
 *	Total Size: 1 * 697600 + 4 (header) = 697644 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/suinyun/Desktop/Spring2019/CS2261/M04/startMusic.wav
 *	Time-stamp: Thu Apr 18 00:08:11 2019
 *	
 **************************************************************/

#ifndef __STARTMUSICH__
#define __STARTMUSICH__

#define STARTMUSICFREQ 11025
#define STARTMUSICLEN 697600

extern const unsigned char startMusic[697600];

#endif /* __STARTMUSICH__ */
