
/**************************************************************
 *	
 *	winSong, 8 bit, 11025Hz,
 *	1 channel, 302688 bytes/channel
 *	Total Size: 1 * 302688 + 4 (header) = 302732 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/suinyun/Desktop/Spring2019/CS2261/M04/winSong.wav
 *	Time-stamp: Thu Apr 18 00:09:07 2019
 *	
 **************************************************************/

#ifndef __WINSONGH__
#define __WINSONGH__

#define WINSONGFREQ 11025
#define WINSONGLEN 302688

extern const unsigned char winSong[302688];

#endif /* __WINSONGH__ */
